services:
  mongo:
    build: .
    container_name: test_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app_network

  backend:
    build: .
    container_name: my_backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://admin:password123@mongo:27017/mydatabase?authSource=admin
      PORT: 3000
    depends_on:
      - mongo
    networks:
      - app_network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  app_network:
    driver: bridge
